name: Trigger Remote Workflow
permissions: write-all
env:
  repository: '${{ secrets.owner_repo }}/${{ secrets.repo }}'
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Check github connection
        id: check-gh
        run: bash connection.sh
      - name: Check new patch ReVanced
        id: check-rv
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash ci.sh ReVanced/revanced-patches latest youtube-revanced.apk
      - name: Check new patch ReVanced Beta
        id: check-rv-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash ci.sh ReVanced/revanced-patches prerelease youtube-beta-revanced.apk
      - name: Check new patch Revanced Extended forked by Anddea Stable Version
        id: check-rve-anddea-stable
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash ci.sh anddea/revanced-patches latest youtube-stable-anddea.apk
      - name: Check new patch Revanced Extended forked by Anddea Beta Version
        id: check-rve-anddea-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash ci.sh anddea/revanced-patches prerelease youtube-beta-anddea.apk
      - name: Check new patch Twitter Piko Stable
        id: check-twitter-piko-stable
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash ci.sh crimera/piko latest twitter-stable-piko.apk
      - name: Check new patch Twitter Piko Beta
        id: check-twitter-piko-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash ci.sh crimera/piko prerelease twitter-beta-piko.apk
      - name: Check new patch Revanced Extended
        id: check-rve
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash ci.sh inotia00/revanced-patches latest youtube-revanced-extended.apk
      - name: Check new patch Revanced Extended Beta
        id: check-rve-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash ci.sh inotia00/revanced-patches prerelease youtube-beta-revanced-extended.apk
      - name: Check new patch Revanced For Android 6 & 7
        id: check-rve67
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash ci.sh kitadai31/revanced-patches-android6-7 latest youtube-revanced-extended-android-6-7.apk
      - name: Check new patch Revanced For Android 5
        id: check-rve5
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash ci.sh d4n3436/revanced-patches-android5 latest youtube-revanced-extended-android-5.apk
      - name: Check new patch BiliRoamingM
        id: check-BiliRoamingM
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash ci.sh sakarie9/BiliRoamingM latest bilibili-BiliRoamingM.apk
      - name: Check new patch Revanced Experiments
        id: check-Revanced-Experiments
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash ci.sh Aunali321/ReVancedExperiments latest telegram-revanced-experiments.apk 
      - name: Keep workflow run
        if: steps.check-gh.outputs.internet_error == '0'
        uses: gautamkrishnar/keepalive-workflow@v1
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 100
    outputs:
      check_rv: ${{ steps.check-rv.outputs.new_patch }}
      check_rv_beta: ${{ steps.check-rv-beta.outputs.new_patch }}
      check_rve_anddea_stable: ${{ steps.check-rve-anddea-stable.outputs.new_patch }}
      check_rve_anddea_beta: ${{ steps.check-rve-anddea-beta.outputs.new_patch }}
      check_twitter_piko_stable: ${{ steps.check-twitter-piko-stable.outputs.new_patch }}
      check_twitter_piko_beta: ${{ steps.check-twitter-piko-beta.outputs.new_patch }}
      check_rve: ${{ steps.check-rve.outputs.new_patch }}
      check_rve_beta: ${{ steps.check-rve-beta.outputs.new_patch }}
      check_rve67: ${{ steps.check-rve67.outputs.new_patch }}
      check_rve5: ${{ steps.check-rve5.outputs.new_patch }}
      check_BiliRoamingM: ${{ steps.check-BiliRoamingM.outputs.new_patch }}
      check_Revanced_Experiments: ${{ steps.check-Revanced-Experiments.outputs.new_patch }}

  trigger:
    name: Trigger workflow
    needs: check
    if: ${{ needs.check.outputs.check_rv == '1' || needs.check.outputs.check_rv_beta == '1' || needs.check.outputs.check_rex == '1' || needs.check.outputs.check_rve_anddea_stable == '1' || needs.check.outputs.check_rve_anddea_beta == '1' || needs.check.outputs.check_rve_rufusin == '1' || needs.check.outputs.check_rve == '1' || needs.check.outputs.check_rve_beta == '1' || needs.check.outputs.check_twitter_piko_stable == '1' || needs.check.outputs.check_twitter_piko_beta == '1' || needs.check.outputs.check_rve67 == '1' || needs.check.outputs.check_rve5 == '1' || needs.check.outputs.check_BiliRoamingM == '1' || needs.check.outputs.check_Revanced_Experiments == '1' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Latest Workflow Run Status
        id: check-latest-run-1
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ownerRepo = `${{ secrets.owner_repo }}`;
            const repoName = `${{ secrets.repo }}`;
            const completedRuns = await github.rest.actions.listWorkflowRuns({
              owner: ownerRepo,
              repo: repoName,
              workflow_id: 'ci.yml',
              status: 'completed',
              per_page: 1
            });
            const runningRuns = await github.rest.actions.listWorkflowRuns({
              owner: ownerRepo,
              repo: repoName,
              workflow_id: 'ci.yml',
              status: 'in_progress',
              per_page: 1
            });
            const hasCompletedRunFailed = completedRuns.data.workflow_runs.length > 0 && completedRuns.data.workflow_runs[0].conclusion !== 'success';
            const hasRunningJobs = runningRuns.data.workflow_runs.length > 0;
            if(hasCompletedRunFailed || hasRunningJobs) {
              core.setOutput('run_next_workflow1', 'false');
              core.setFailed('A job is currently running, or the last completed workflow run failed.');
            } else {
              core.setOutput('run_next_workflow1', 'true');
            }
      - name: Check Latest Workflow Run Status
        id: check-latest-run-2
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ownerRepo = `${{ secrets.owner_repo }}`;
            const repoName = `${{ secrets.repo }}`;
            const completedRuns = await github.rest.actions.listWorkflowRuns({
              owner: ownerRepo,
              repo: repoName,
              workflow_id: 'manual-patch.yml',
              status: 'completed',
              per_page: 1
            });
            const runningRuns = await github.rest.actions.listWorkflowRuns({
              owner: ownerRepo,
              repo: repoName,
              workflow_id: 'manual-patch.yml',
              status: 'in_progress',
              per_page: 1
            });
            const hasCompletedRunFailed = completedRuns.data.workflow_runs.length > 0 && completedRuns.data.workflow_runs[0].conclusion !== 'success';
            const hasRunningJobs = runningRuns.data.workflow_runs.length > 0;
            if(hasCompletedRunFailed || hasRunningJobs) {
              core.setOutput('run_next_workflow2', 'false');
              core.setFailed('A job is currently running, or the last completed workflow run failed.');
            } else {
              core.setOutput('run_next_workflow2', 'true');
            }           
      - name: Trigger the Workflow
        if: ${{ steps.check-latest-run-1.outputs.run_next_workflow1 == 'true' && steps.check-latest-run-2.outputs.run_next_workflow2 == 'true' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: "${{ secrets.owner_repo }}",
              repo: "${{ secrets.repo }}",
              workflow_id: "ci.yml",
              ref: "main"
            })
